# Generated by Django 4.0 on 2022-08-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de creación')),
                ('nif', models.CharField(max_length=100, verbose_name='NIF')),
            ],
        ),
    ]
