# Generated by Django 4.0 on 2022-08-14 20:12

from django.db import migrations, models
import institutions_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('institutions_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='nif',
            field=models.CharField(max_length=9, validators=[institutions_app.validators.validate_nif], verbose_name='NIF'),
        ),
    ]
